### ISSUE TITLE
Separate Out Generators

### ISSUE THREAD

**Issue by nahtnam** [ghaiklor/generator-sails-rest-api#100]
Hey!

It would be great if generators were separated out. For example, I want to use this app, but keep the default blueprints because I am using https://github.com/huafu/ember-data-sails to consume it.

Same applies for things like authentication, and services.

What would be even better is if we could use these generators on top of an existing app. So we can do things like `yo sails authentication` and it would generate everything needed for authentication. We would also need `yo sails init` to remove things like csrf, grunt, i18n, pubsub, session, and views.

Thoughts?

Thanks.

**Comment by ghaiklor** [comment]
@nahtnam already in progress, you can check out `dev` branch :smiley: 
I've split all the parts of the `api` folder to separate generators, so you able to call only what you need.

Here is the list of all generators - https://github.com/ghaiklor/generator-sails-rest-api/tree/dev/src
