### ISSUE TITLE
Is Model.Count(where) best implementation 

### ISSUE THREAD

**Issue by hjain-spcg** [ghaiklor/generator-sails-rest-api#105]
https://github.com/ghaiklor/generator-sails-rest-api/blob/dev/src/blueprints/templates/api/blueprints/find.js

 let countQuery = Model.count(where);

The problem I was facing was that back end table has 67K+ records.  So I decide to use limit as parameter to lets say 1000 or user defined value, such that user should expect longer times for more records.  For my purpose was ok.   Tracing through the code on the SQL adapter the limit clause turns into TOP @limit clause.   So great, however, Model.count(where) comes as additional query and retrieves all records and then does count after the serialization to the web/app server?  Would it be better to do explicit query call and/or does it vary with respect backing datastore ?

**Comment by ghaiklor** [comment]
@hjain-spcg we had trying to accomplish this with custom blueprint but Sails doesn't allow to do this.

My vision was to add `count` blueprint that binds to `:model/count` route, but it can't be achieved.

If you have any suggestions how to implement this, I will be glad :smiley_cat:

**Comment by IncoCode** [comment]
```js
import _ from 'lodash';
import actionUtil from 'sails/lib/hooks/blueprints/actionUtil';
import pluralize from 'pluralize';

let countBlueprint = (req, res) => {
  let Model = actionUtil.parseModel(req);
  let countQuery = Model.count();

  countQuery
    .then(count => {
      res.ok({ count: count })
    });
};

export default function (sails) {
  var config = sails.config.blueprints;

  return {
    initialize: cb => {
      sails.on('router:before', () => {
        let countFn = sails.middleware.blueprints.count || countBlueprint;

        _.forEach(sails.models, model => {
          if (!_.get(sails.middleware.controllers, model.identity)) return;

          let baseRoute = [config.prefix, model.identity].join('/');
          if (config.pluralize) {
            baseRoute = pluralize(baseRoute);
          }
          let route = baseRoute + '/count';
          sails.router.bind(route, countFn, null, { controller: model.identity });
        });

      });

      cb();
    }
  }
};
```

**Comment by ghaiklor** [comment]
@IncoCode good work. I'd done review of your code and will merge it when it will be done.

**Comment by ghaiklor** [comment]
We have an implemented hook for count blueprint, thanks to @IncoCode

**Comment by gustperz** [comment]
how to get only GET:count?

**Comment by mikedevita** [comment]
i wanted to add a count to the pager stuff that shows you the total number of rows based on your query but not sure how to modify the `find()` blueprint..

```
{
  limit: 20,
  start: 0,
  end: 20,
  total: 100
}
```
