### ISSUE TITLE
Consistent Sub-Generators API

### ISSUE THREAD

**Issue by ghaiklor** [ghaiklor/generator-sails-rest-api#107]
Here is an examples of calling sub-generators. Each sub-generator MUST contain following options\arguments:

```shell
yo sails-rest-api:service # Runs interactive mode with questions
yo sails-rest-api:service --all # Copies all the predefined services
yo sails-rest-api:service MyService # Scaffolds MyService from predefined file (if exists)
yo sails-rest-api:service MyService --new # Scaffolds MyService from generic template
```

**Comment by ghaiklor** [comment]
Another option is to run all the generators in interactive mode, but fill questions' defaults from arguments\options.

@IncoCode still need to research about this. And if we run all generators in interactive mode then how can we handle `composeWith` ?

**Comment by ghaiklor** [comment]
Implemented the case above for all generators and checked - API is consistent :+1:

**Comment by BraunreutherA** [comment]
You should put this into the docs - didn't find it there and had to search the issues.

**Comment by ghaiklor** [comment]
@BraunreutherA what exactly ? Each sub-generator has help command where you can read this.

**Comment by BraunreutherA** [comment]
Ah okay didn't know that - I was confused cause the other sub generators are documented (e.x. model or config) and the service generation not.
