### ISSUE TITLE
babel hook

### ISSUE THREAD

**Issue by BraunreutherA** [ghaiklor/generator-sails-rest-api#126]
hey there,

why not using the sails babel hook? https://github.com/artificialio/sails-hook-babel

**Comment by ghaiklor** [comment]
@BraunreutherA `sails-hook-babel` is start to initialize only after some code execution. So not the whole project can be written in ES6 syntax. Running it with `babel-node` I can guarantee that all you project can be written with ES6 syntax.

For instance, when you are using `sails-hook-babel` you are not able to write configuration files in ES6 syntax and getting an error.

**Comment by BraunreutherA** [comment]
Ah okay, thank you for the explanation :+1:
