### ISSUE TITLE
Add code coverage for es6 

### ISSUE THREAD

**Issue by BraunreutherA** [ghaiklor/generator-sails-rest-api#127]
hey there, 

you should add code coverage for es6 - isparta is very easy to use on top of istanbul.

**Comment by ghaiklor** [comment]
@BraunreutherA I'll try. Wondering how it works with isparta.

**Comment by ghaiklor** [comment]
@BraunreutherA I couldn't run tests with `bootstrap.js` file :smiley_cat: I have debugged that `before` and `after` is just not calling.

**Comment by BraunreutherA** [comment]
Jeah, but I don't think its a problem with isparta. I tried it even with plain mocha and they aren't executed.

**Comment by ghaiklor** [comment]
@BraunreutherA Just pushed new changes to `dev`, check it out.

**Comment by ghaiklor** [comment]
@BraunreutherA yeah, I know. The same, try to running just mocha and nothing.

**Comment by BraunreutherA** [comment]
I think the problem is because you are using bootstrap.js in the mocha require command which doesn't support before and after

**Comment by ghaiklor** [comment]
@BraunreutherA I pushed new changes to dev branch. I've moved from `--require` to just calling it as test. The same behaviour.

**Comment by BraunreutherA** [comment]
You could place bootstrap.js in unit and run recursively the unit test. That way it gets executed first. But another problem occurs: In the services the sails global object ist used for config - so whenever you import a service you'll get an error, because it tries to acces the sails object. So we would need the sails lift executed before the tests are executed.

**Comment by BraunreutherA** [comment]
> Try to console.log() in before hook and you see that it's even not calls 
that's why it errors before

**Comment by ghaiklor** [comment]
@BraunreutherA now it's running but... Try to remove all test files and left only bootstrap. In before hook make console.log and run test. You will see that tests is successful, but you will not see your log. It's fucking strange :(

**Comment by ghaiklor** [comment]
Maybe Babel is modifying runtime somehow ?

**Comment by BraunreutherA** [comment]
I know, did this the whole day. It's a simple thing: 

/Users/braunreu/Desktop/instantley/api_v1/api/services/CipherService.js:13
var jwt = (0, _sailsServiceCipher2['default'])('jwt', sails.config.services.cipher.jwt);

That's the error we get - have a look into your CipherService file It uses: 
sails.config.services.cipher.jwt

So it needs the sails global object which would get created when before gets executed. It only gets executed when it comes to an describe block. But it won't get to a describe block because the error gets thrown before when it tries to pull in the service.

**Comment by BraunreutherA** [comment]
There are some ways - 1. stub out the sails config 2. create somehow the sails object and make it available before the other test files get executed

**Comment by ghaiklor** [comment]
There is one thing that I'm also tried to achieve. In before hook wrote global.sails = server. Didn't help though.

**Comment by ghaiklor** [comment]
I think that issue in Babel and mocha. Because with ES5 it worked.

**Comment by BraunreutherA** [comment]
I'm working on a solution where I wrap mocha in a script. Let's see :)

**Comment by BraunreutherA** [comment]
https://gist.github.com/BraunreutherA/f086bca58a5a3b9d5ed1

this works but needs some more love

**Comment by IncoCode** [comment]
@BraunreutherA can you please create a pr?

**Comment by BraunreutherA** [comment]
I'd like to but that's not a good way yet cause it doesn't work with coverage very well.  I'll start a PR when I found a good way
