### ISSUE TITLE
How to create a new controller using command?

### ISSUE THREAD

**Issue by akshath4u** [ghaiklor/generator-sails-rest-api#128]
Hi,

Could you please suggest me to create  a new controller using command in this scaffold (like 'sails generate sleep' in sail)

**Comment by ghaiklor** [comment]
@akshath4u as I suppose, you're using next version from npm? In this case just call `yo sails-rest-api:controller Sleep`

**Comment by akshath4u** [comment]
@ghaiklor Thank you :+1:

**Comment by akshath4u** [comment]
Hi,

While i'm trying to create a controller using the command `yo sails-rest-api:controller Devices create find` this will ask for database and all the steps which come across creating project structure using `yo sails-rest-api`. 
![selection_009](https://cloud.githubusercontent.com/assets/9428527/10757014/dde4fbc4-7ccd-11e5-958b-4038cdbc7678.png)

**Comment by ghaiklor** [comment]
@akshath4u Yours version is 0.10.7 which is the latest. There is no functionality like you asked. Only in `@next` version from npm.
