### ISSUE TITLE
Express and bluebird missing for swagger

### ISSUE THREAD

**Issue by BraunreutherA** [ghaiklor/generator-sails-rest-api#130]
Hi there, 

when running my tests it complains that express and bluebird is missing. It is required by the swagger hook. I don't know which generator part should install this dependencies so I can't do a PR

**Comment by ghaiklor** [comment]
@BraunreutherA all parts of the Sails project is split to separate folders. For instance, you have issue with `swagger`, you just need get a look into `src/swagger` folder.

BTW, I've removed a lot of tests because they written awful and need to re-write them.

**Comment by ghaiklor** [comment]
@BraunreutherA I'd trying to reproduce this issue when running tests - nothing. Could you try the latest version, may be that it already fixed.
