### ISSUE TITLE
How do I use the generator with Babel in production?

### ISSUE THREAD

**Issue by weyert** [ghaiklor/generator-sails-rest-api#132]
Could you give me some hints how I can use Babel with your awesome seed project? Based on resources on the internet use babel-node is not a good idea for production. Any tips?

I have to admit I don't have much experience with Babel yet. Especially, in combination with Sails.js. Thanks.

**Comment by ghaiklor** [comment]
@weyert `babel-node` is not good idea for npm modules. But if you are developing your own web-server that doesn't affect other users, you can use `babel-node`.

Anyway, you can make mirroring as I have done in generator's sources. Create src folder where you locate ES6 sources files and configure Babel to compile it into `api` folder. Then run Sails as usual.

**Comment by weyert** [comment]
Thanks, I will give this a shot.
