### ISSUE TITLE
Configuration issue when using MailService

### ISSUE THREAD

**Issue by weyert** [ghaiklor/generator-sails-rest-api#134]
If you using Sendgrid together with the MailService when generating a new project. You are getting an error that the configuration options are missing.

**Comment by ghaiklor** [comment]
@weyert that's because you should configure it with your API keys. What've you expected?

**Comment by weyert** [comment]
Ah, I would have thought maybe some dummy configuration?

**Comment by ghaiklor** [comment]
@weyert You can read more docs on appropriate repository. In your case you are using MailerService. So you should take a look here for [configuring section](https://github.com/ghaiklor/sails-service-mailer#configuration)

My generator just include these services, but can't configure them because too many edge-cases.

**Comment by weyert** [comment]
Ah sorry Eugene, I somehow imagined it to be a ready made thing. As you
generate it and you have a working version. My apologies, for being stupid!
One of those days, I guess :)

**Comment by ghaiklor** [comment]
@weyert I should document this, I suppose :)

**Comment by prisonier** [comment]
I just had the same issue. 

Couldn't you create a basic configuration that doesn't throw an exception ?

I think it would be more straight forward for people to being able to lift their app just after using the genrator.

**Comment by ghaiklor** [comment]
@prisonier it doesn't resolve the issue. Each provider has different configuration fields. Secondly, if I make default working configuration, you forgot to configure service and starts create issue that sending mail is not working :)

**Comment by l1br3** [comment]
@ghaiklor I started a new project with the generator, and it took me few minutes to remember this issue. I think you should put some default configuration because `npm start` after install fails.

**Comment by ghaiklor** [comment]
@l1br3 I already mentioned why it could leads to more difficult errors. That way, you got errors, other way you propose, you got nothing in logs and nothing is working.

**Comment by l1br3** [comment]
@ghaiklor that's not correct, you will get an error when you will try to send a mail. Something like 'impossible to connect to sendgrid with the api key "change_this_api_key" '

This is far better than having an error at npm start without any explanation on how to configure the mailer service.

**Comment by ghaiklor** [comment]
@l1br3 that's for your case. Other provider could not throw an error and proceed silent. You need to understand, that I have a lot of different services, which are implemented differently under the hood in provider.

**Comment by l1br3** [comment]
I don't say that my solution is good for all cases, I just say that having an non understable error at first npm start is not optimum.
