### ISSUE TITLE
How to use the Facebook authentication?

### ISSUE THREAD

**Issue by weyert** [ghaiklor/generator-sails-rest-api#135]
I was wondering how you had the Facebook authentication in mind. If I understood the source code correctly after obtaining the access token (e.g. via the FB iOS SDK). The Facebook strategy can be called like so: http://localhost:3000/v1/auths/social/?type=facebook&access_token=[token]. 

Only when I try to do a request like this with or without the `access_token`-parameter I am getting the following error: 

{
  "code": "E_INTERNAL_SERVER_ERROR",
  "message": "Cannot read property 'onPassportAuth' of undefined",
  "data": {}
}
(maybe _.partial() is failing on line 52 of AuthController.js?)

I am not seeing where this is coming from because there is a method called onPassportAuth in the codebase. Why can't it find it?

Also I don't understand why the `jwt`-strategy is being referred to while trying to log into the site by using the social network. Wouldn't a successful login invoke the callback (nowhere defined/implemented?) which then can be used to create a user record when it's not existing for the social network unique identifier (E.g. facebookId?).

Thanks.

Regarding reproducing: I have chosen local database, no controllers, no swagger, no services but cipher and hash, authenticated enabled.

**Comment by IncoCode** [comment]
> (maybe _.partial() is failing on line 52 of AuthController.js?)

`onPassportAuth` function is exported to `sails.config`: https://github.com/ghaiklor/generator-sails-rest-api/blob/v1.0.4/src/authentication/templates/config/passport.js#L148
In `AuthController` we expect that this function is in `sails.config.passport`: https://github.com/ghaiklor/generator-sails-rest-api/blob/v1.0.4/src/authentication/templates/api/controllers/AuthController.js#L50

**Comment by weyert** [comment]
Yes, that's why I don't fully understand why this error occurs as the function definition exists.

**Comment by weyert** [comment]
Yes, working now. Awesome.
