### ISSUE TITLE
Add password check for in base implementation User-model

### ISSUE THREAD

**Issue by weyert** [ghaiklor/generator-sails-rest-api#136]
Currently, when you use the social signup approach a User-model gets created which then fails because the beforeCreate-hook of the User-model is trying to encrypt the password which is non available.

I would consider adding the following as the only function of the beforeCreate and beforeUpdate is to bcrypt the password:

    if (false === values.hasOwnProperty('password')) return next()

This avoids the E_UNKNOWN error when signing up through a social network.

**Comment by ghaiklor** [comment]
@weyert I've merged your PR but I can't publish it because your commits is not following the spec. So semantic-release can't generate changelog and make publish. It will be published later.

**Comment by ghaiklor** [comment]
@weyert published it manually. If you will make another PRs, use commitizen for commits, please. I'm using `semantic-release` that publishes and generates changelog automatically. And if commits messages is not valid then semantic-release can't parse it and make publish.

**Comment by weyert** [comment]
Never heard of commitizen. What's that?

**Comment by ghaiklor** [comment]
@weyert it's a tool that you can use as `git cz` command in your terminal - http://commitizen.github.io/cz-cli/
