### ISSUE TITLE
How to set api_key for Swagger UI Explorer?

### ISSUE THREAD

**Issue by bossyang** [ghaiklor/generator-sails-rest-api#148]
Or is there default api_key for demonstration purpose?

**Comment by ghaiklor** [comment]
@bossyang you can disable policy for `DocsController`, if you want to show Explorer without api key. There is still a question how to add support for Bearer tokens in Explorer.

**Comment by bossyang** [comment]
@ghaiklor  Thanks. Is this normal?
````
No package information
You should set sails.config.swagger.pkg to retrieve the content of the package.json file
````
And the operations are not quite right.
![sails-swagger-list-operations](https://cloud.githubusercontent.com/assets/2443508/10900330/5e4fb498-8219-11e5-8ee0-eb092d23f9b3.png)

**Comment by ghaiklor** [comment]
@bossyang we are using this hook https://github.com/tjwebb/sails-swagger for collecting data.

I know about these issues but can do nothing with it :(

**Comment by evereq** [comment]
@bossyang seems I found a way to get rid of this message about missing package info (Swagger wants to read your project name and description from it).

In the config folder of your sails app, create file swagger.js with something like:

``` JavaScript
// config/swagger.js
module.exports.swagger = {
  /**
   * require() the package.json file for your Sails app.
   */
  pkg: require('../package'),
  ui: {
    url: 'http://swaggerui.balderdash.io'
  }
};
```

@ghaiklor can also create such config file in the yo generator some day....

**Comment by ghaiklor** [comment]
@IncoCode could you add config for our explorer ?

**Comment by bossyang** [comment]
@evereq Thanks. It works!
And where to set the default url?
![swagger-ui-default-url-issue](https://cloud.githubusercontent.com/assets/2443508/11521774/b3a3629a-98ea-11e5-8136-94366063ad54.png)

**Comment by evereq** [comment]
@bossyang it's in the ```explorer/index.html``` file

**Comment by bossyang** [comment]
@evereq Thanks. I changed the default to the current url.

```javascript
  <script type="text/javascript">
    $(function () {
      var url = window.location.search.match(/url=([^&]+)/);
      if (url && url.length > 1) {
        url = decodeURIComponent(url[1]);
      } else {
        var base_url = window.location.origin;
        url = base_url + "/v1/Docs/";
      }
````

**Comment by ghaiklor** [comment]
@bossyang @evereq so what's the question? Do we need to add `swagger` config?

**Comment by bossyang** [comment]
@ghaiklor Yes, please.
