### ISSUE TITLE
JWT query parameter access_token doesn't work

### ISSUE THREAD

**Issue by bossyang** [ghaiklor/generator-sails-rest-api#163]
Currently, I can only add the credential through the HTTP Authorization header. 

http://localhost:3000/v1/stores?access_token=eyJ0eXAiOiJK

````json
{
  "code": "E_UNKNOWN",
  "message": "Encountered an unexpected error",
  "data": {
    "raw": {
      "code": "ER_BAD_FIELD_ERROR",
      "errno": 1054,
      "sqlState": "42S22",
      "index": 0
    }
  }
}
````
Change to default parameter name __auth_token__.
http://localhost:3000/v1/stores?auth_token=eyJ0eXAiOiJKV1QiLCJhb
````json
{
  "code": "E_INTERNAL_SERVER_ERROR",
  "message": "No auth token",
  "data": {}
}
````

**Comment by ghaiklor** [comment]
@bossyang Try to add `access_token` to blacklist in `find` blueprint. When you are passing `access_token` like this, Sails is thinking that this is field of your model and trying to find with that criteria.
Open `blueprints/find.js` and add `access_token` to array of blacklist.

**Comment by bossyang** [comment]
@ghaiklor Thanks.
