### ISSUE TITLE
Build to es5

### ISSUE THREAD

**Issue by toddgeist** [ghaiklor/generator-sails-rest-api#166]
If I understand this correctly, projects created with this generator are transpiled on the fly to es5.  This seems fine for development work.  But is this a good idea in production?  Is there a build task that transpile the whole app?

Thanks

Todd

**Comment by ghaiklor** [comment]
@toddgeist no, because we need to store sources and transpiled core separately then. If you know the good way to store sources and transpiled code without breaking Sails concepts then let me know :smiley_cat:

**Comment by toddgeist** [comment]
I was hoping you had figured it out :-)
