### ISSUE TITLE
Error: Cannot find module 'passport-twitter-token'

### ISSUE THREAD

**Issue by c835722** [ghaiklor/generator-sails-rest-api#17]
Hi. I like what you have done here.
After npm install;sails lift I got the above error. The generated package.json seemed to be missing passport-twitter-token package. 
I executed a npm install passport-twitter-token and all good.
Keep up the good work. 
Cheers.

**Comment by ghaiklor** [comment]
@c835722 Hi. Thanks, I appreciate it. I already fix that error in edge version and very soon will publish update.

Here still a lot of work, and stability only in Experimental level, but in general all works fine now. The one place where errors still left - `services`. But I'm working on it. Thanks for issue report :+1:

**Comment by ghaiklor** [comment]
Here is the commit which fix the bug - 5b9df99bfae57aeafd1777078f4773aee5eb9338

**Comment by c835722** [comment]
oh yes I see. Following the readme.md via yeoman I would have gone the public npm route and thus not picked up the dev branch. I will git clone. Ta.

**Comment by c835722** [comment]
And [here](http://stackoverflow.com/questions/23657971/installing-yeoman-generator-globally-using-npm-and-github-fork-for-development) is an example of how to install a github dev branch into Yeoman. This might be worthwhile in a FAQ/Wiki sometime in the future.

**Comment by ghaiklor** [comment]
@c835722 I'll describe how install edge version of generator in README today after I done with customMiddleware approach and swagger documentation :smiley:
