### ISSUE TITLE
npm install fails on node 4.2.2

### ISSUE THREAD

**Issue by tjwebb** [ghaiklor/generator-sails-rest-api#171]
I clone, and run `npm install`. I get this error:

```
SyntaxError: src/config/templates/config/cors.js: Unexpected token (14:15)
  12 |      * Allow CORS on all routes by default?
  13 |      */
> 14 |     allRoutes: <%= options["cors"] %>,
     |                ^
  15 |
  16 |     /**
  17 |      * Which domains which are allowed CORS access?
```

node 4, npm 2.14

**Comment by tjwebb** [comment]
I just checked out 1.1.0 and install works fine on that tag.

**Comment by ghaiklor** [comment]
@tjwebb seems you'd checkout dev branch which is in progress of migration to Babel 6. Master branch is stable if you want to test out features.
