### ISSUE TITLE
password lifecycle beforeUpdate

### ISSUE THREAD

**Issue by rizr** [ghaiklor/generator-sails-rest-api#18]
beforeUpdate User model need to check new pass then only to hash pass again;
like this :
    beforeUpdate: function(values, next) {
        if (typeof values.newPassword != 'undefined' && values.newPassword !== '')

 becouse we have problem with forgot pass:
    user.password = CipherService.create('bcrypt', {content: newPassword}).hashSync();

**Comment by ghaiklor** [comment]
@rizr the issue here that `newPassword` doesn't corresponds to real `User` model. So need to think here how this can be accomplished in other way, without `newPassword` value.

**Comment by ghaiklor** [comment]
This logic must be implemented in controller. Closing this issue.
