### ISSUE TITLE
shasum check fails on latest update

### ISSUE THREAD

**Issue by myspivey** [ghaiklor/generator-sails-rest-api#196]
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3

npm ERR! shasum check failed for /tmp/npm-37464-cec2e633/registry.npmjs.org/generator-sails-rest-api/-/generator-sails-rest-api-1.2.0.tgz
npm ERR! Expected: 84a1fcf62adcb979de16e98ea4ee169cfed4fbf7
npm ERR! Actual:   283f59efa236338132669827a5f070c5a6e35592
npm ERR! From:     https://registry.npmjs.org/generator-sails-rest-api/-/generator-sails-rest-api-1.2.0.tgz

**Comment by ghaiklor** [comment]
@myspivey node 4.2.6, npm 3.6.0, works fine. This issue is npm-related issue, try to upgrade npm.

**Comment by Salakar** [comment]
3.5.3 is the latest npm. 3.5.4 and 3.6.0 are both pre-release. Doesn't work on 3.5.3 for me either.

**Comment by ghaiklor** [comment]
@Salakar can be related to this issue - https://github.com/npm/npm/issues/2701

**Comment by Salakar** [comment]
Hmm, i tried cache clean and resetting the registry, didn't work - I'll just extract it manually to the global node_modules folder.

**Comment by ghaiklor** [comment]
@Salakar I'll try install generator again tomorrow morning. For now, I marked this as a bug in generator but I believe this is npm related issue.

**Comment by Ivan-Feofanov** [comment]
using npm 3.3.6 - same trouble

**Comment by ghaiklor** [comment]
@Ivan-Feofanov @Salakar @myspivey fixed in 1.3.1
