### ISSUE TITLE
Implement all tests

### ISSUE THREAD

**Issue by ghaiklor** [ghaiklor/generator-sails-rest-api#20]
I add boilerplate for tests here #11 and now need just fill them with test cases. Big task, so need make it in another branch and then merge it.

**Comment by IncoCode** [comment]
Each service has its own tests. Can we just copy/paste them here? :smile:

**Comment by ghaiklor** [comment]
@IncoCode services is different. We don't need to cover them with tests, just require at all. We need tests only for all stuff under `api` folder - #54

**Comment by ghaiklor** [comment]
OK, so basically we cover all the required controllers\models\etc... From now we can just improve this test coverage with time.
