### ISSUE TITLE
Cant run

### ISSUE THREAD

**Issue by tosbaha** [ghaiklor/generator-sails-rest-api#207]
I installed as it is stated in readme file. I didn't change anything and selected default options always by hitting enter. When I first start it failed because of missing express dependency. I installed missing dependency then it started. I also created the models yo sails-rest-api:model Ticket but I can't test the api. http://localhost:3000 only shows

```
{
  "code": "E_NOT_FOUND",
  "message": "The requested resource could not be found but may be available again in the future",
  "data": {}
}
```

**Comment by ghaiklor** [comment]
@tosbaha https://github.com/ghaiklor/generator-sails-rest-api/wiki/Sub-Generators#list-of-controllers

**Comment by tosbaha** [comment]
`yo sails-rest-api:controller Ping`

http://localhost:3000/v1/ping

```
{
  "code": "E_INTERNAL_SERVER_ERROR",
  "message": "No auth token",
  "data": {}
}
```
`yo sails-rest-api:controller Search`
http://localhost:3000/v1/search?q=text
```
{
  "code": "E_INTERNAL_SERVER_ERROR",
  "message": "No auth token",
  "data": {}
}
````

I am trying to create a basic api for user(add/delete/update/changepasss) and todoitem(add/delete/update) I will really appreciate if you can help me on this.

**Comment by ghaiklor** [comment]
@tosbaha Message in response says that you don't provide auth token. If you don't want authorization layer then don't generate it when scaffolding the project.
