### ISSUE TITLE
Why drop babel

### ISSUE THREAD

**Issue by BraunreutherA** [ghaiklor/generator-sails-rest-api#211]
Hey there,

is there a reason why you dropped babel support?

Best regards,
Alex

**Comment by ghaiklor** [comment]
@BraunreutherA hey, yes. I'd use babel-node CLI for running Sails applications which is decrease the overall perfomance of the web-server. Starting from NodeJS 4 you can write many of ES6 features with native support without Babel. So I dropped Babel, allowing to you, as a developer, write ES6 code which NodeJS 4 supports and for V8, as a VM which executes JavaScript, possibilities to optimize ES6 code, not the transpiled ES5.

**Comment by BraunreutherA** [comment]
Wouldn't be a compiled version suitable? so just for development using the cli with the babel-node command and before using the stack in production let babel compile it completely so u have no performance hits. But you're right node 4 brings a lot es6 into the game.

**Comment by ghaiklor** [comment]
@BraunreutherA I don't think making these steps is great idea. NodeJS 0.10 and 0.12 remains on legacy projects only. Everyone install the latest NodeJS versions :)
