### ISSUE TITLE
`make` failed with exit code: 2 for kerberos during install (Linux)

### ISSUE THREAD

**Issue by prisonier** [ghaiklor/generator-sails-rest-api#213]
Hi, I get this error on linux during install (after configuration).

```javascript
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/libre/.nvm/versions/node/v4.3.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/home/libre/.nvm/versions/node/v4.3.1/bin/node" "/home/libre/.nvm/versions/node/v4.3.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/libre/dev/test/node_modules/kerberos
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

I had to install packet libkrb5-dev according to this [issue](https://github.com/christkv/kerberos/issues/21) 

Maybe you should document that this package is necessary on linux systems ?
According to kerberos readme, there other packages necessary like build-essentials, gcc and g++.

**Comment by ghaiklor** [comment]
@prisonier may it be some specific case for your machine? You're the first one with that issue.

**Comment by prisonier** [comment]
I think it is because I used a very fresh linux install and some packages wasn't installed. 

It is not really related to your work because it is a dependency of sails-mongo.

Anyway, if someone has the problem, he will find the solution here :)

**Comment by ghost** [comment]
I had this issue today running fresh install of Linux Mint 18.3 Cinnamon
