### ISSUE TITLE
Error in wiki - sub generators - cors

### ISSUE THREAD

**Issue by prisonier** [ghaiklor/generator-sails-rest-api#214]
Hi,

Just a small issue in the doc : 

CORS allows to you make requests from client-side JavaScript. By default, it's disabled, but you can enable it if you wish.

```javascript
yo sails-rest-api:config --cron # Enables cron by default
yo sails-rest-api:config --no-cron # Disables cron by default
```

You've written cron instead of cors

**Comment by ghaiklor** [comment]
@prisonier fixed.
