### ISSUE TITLE
Feature Request : having something like sails-hook-autoreload in dev

### ISSUE THREAD

**Issue by prisonier** [ghaiklor/generator-sails-rest-api#215]
As the title says I love this module -> [sails-hook-autoreload](https://github.com/sgress454/sails-hook-autoreload)

This hook is quite usefull for dev and I always use it. Unfortunately as it reloads many sails vanilla hooks it doesn't work with your scaffold.

If you know a better solution for avoiding lower/lift the app I would be happy to know it !

Thanks again for your awesome work.

**Comment by ghaiklor** [comment]
@prisonier better to use nodemon package - https://www.npmjs.com/package/nodemon.

**Comment by prisonier** [comment]
The big difference between thoses packages is that nodemon will restart the app while sails-autoreload will only reload some files without restarting the app.

In one case you have to wait 2 or 3 secondes between each changes, in the other case, every change is done immediatly.

I simply commented  the following line in the node module: 

node_modules/sails-hook-autoreload/index.js - line 109
```javascript
            // Reload locales
            //sails.hooks.i18n.initialize(function() {});
```

I don't know if a conflict can exists if you use nodemon with sails-hook-autoreload.

**Comment by ghaiklor** [comment]
I've used nodemon a lot of times and didn't see issues. About your case, I've disabled unneccessary hooks so that your hook-autoreload try to initialize disabled hook.

**Comment by prisonier** [comment]
Yes it what I understood.

I opened an issue on sails-hook-autoreload to ask them to make the i18n hook reload optional to avoid conflicts whith you awesome module.
