### ISSUE TITLE
find blueprint : total count of records

### ISSUE THREAD

**Issue by prisonier** [ghaiklor/generator-sails-rest-api#216]
Hello,

When I do a find request with the blueprint like : 
```
/v1/videos?limit=200
```
I don't have the count of records in the response while it is said in the doc : 

>First of all, it optimises select data from database based on required fields and populates only associations, that you really need to populate. It mixins metadata in the root of a response also, so you know total count of records, criteria, current page, etc...

The response :  
```javascript
{
    "code": "OK",
    "message": "Operation is successfully executed",
    "data": [
        {
            "id": "56c7a0aeb0ac4c060c0fde32"
        },
        {
            "id": "56c7a0c7b0ac4c060c0fde33"
        },
    ],
    "criteria": {},
    "limit": 200,
    "start": 0,
    "end": 200,
    "page": 0
}
```

**Comment by ghaiklor** [comment]
@prisonier try to make request to `v1/users/count`. I don't remember, maybe we moved this to separate route for fixiing perfomance issues.

**Comment by prisonier** [comment]
Yes I forget to say that this url works. I just wanted to point it to be sure that it wasn't a bug but just a doc issue.

**Comment by ghaiklor** [comment]
@prisonier thanks for the report, fixed.

**Comment by prisonier** [comment]
Can I add a where clause on the count method ? 

I tried this without success `/v1/videos/count?channel=1`

**Comment by ghaiklor** [comment]
@prisonier not sure.

@IncoCode it was your feature, can he do it ?

**Comment by prisonier** [comment]
@ghaiklor  Thanks for your answer. With the old feature I could find the number of record for any request. It is sad that we are facing a downgrade. 
I guess it has been removed for performance issues ?

**Comment by IncoCode** [comment]
@prisonier you can always override the count blueprint and add your custom logic.
just copy code of this function https://github.com/ghaiklor/generator-sails-rest-api/blob/dev/generators/hook/templates/api/hooks/CountHook.js#L11 into a separate file called `count.js` (in `blueprints` folder) and improve the code by adding `parseCriteria` etc like here: https://github.com/ghaiklor/generator-sails-rest-api/blob/dev/generators/blueprint/templates/api/blueprints/find.js#L22
