### ISSUE TITLE
how to use socket.io in blueprints

### ISSUE THREAD

**Issue by riyastk** [ghaiklor/generator-sails-rest-api#218]
I need to access the events from blueprints action like create, update and delete from client. How could i use this

**Comment by ghaiklor** [comment]
@riyastk this generator scaffold the project with disabled sockets. You need to do it all manually.

**Comment by riyastk** [comment]
how can i add socket for every add, update and delete operation, so than client get notified

**Comment by ghaiklor** [comment]
@riyastk you better to start with default Sails scaffolder then. The main goal of this generator is to disable all unneeded stuff and override default things.

You can try enable `sockets` hook in `sailsrc` file and remove `blueprints` folder.
