### ISSUE TITLE
Support sails 0.12?

### ISSUE THREAD

**Issue by mikedevita** [ghaiklor/generator-sails-rest-api#225]
Hey is there a plan to update this repo for sails 0.12 support?

**Comment by ghaiklor** [comment]
@mikedevita hey. Yes, I'm working on another project now. I will update generator with some fixes and Sails upgrade in few days.

**Comment by l1br3** [comment]
Hi @ghaiklor, after almost a year I tried to do that but tests fails.
I cloned the repo, [updated package.json](http://pastebin.com/QJq4yf7u), npm install and run tests.

Could you give me some advices to solve issues ? I don't understand the [stack trace](http://pastebin.com/qh07CNmr)

**Comment by ghaiklor** [comment]
@l1br3 do not update dependencies if you want to have working version. Otherwise, you need to migrate current codebase to new API of dependencies.

**Comment by l1br3** [comment]
I tried it with just updating sails to 0.12.4 and I've got exactly the same failures

**Comment by BraunreutherA** [comment]
I did a clean install from the generator and updated to 0.12.11. Then I adjusted the test bootstrap to use sails.load() instead of sails.lift() which is recommended by sails as the tests use sails.request() anyhow. 

That way the test/boostrap.js becomes this: 

```js
"use strict";

const Sails = require('sails');
const config = require('../config/env/test');

before(done => {
  Sails.load(config, (error) => {
    if (error) return done(error);

    done();
  });
});
```

And everything works with sails 12 :)

**Comment by ghaiklor** [comment]
@BraunreutherA can you create a small PR, so I can publish a new version? :)

**Comment by mikedevita** [comment]
PR is inbound for @BraunreutherA's proposed fixes i'm just testing the final parts now.
