### ISSUE TITLE
You don't seem to have a generator with the name sails-rest-api installed, sails 0.12, node 5.6, yo 1.7.

### ISSUE THREAD

**Issue by MohmadAyman** [ghaiklor/generator-sails-rest-api#234]
could you please tell me which version do i have to downgrade to be able to run generator-sails-rest-api?
or is there a solution for this problem ?

**Comment by ghaiklor** [comment]
@MohmadAyman could you paste here full output of your terminal?

`yo sails-rest-api` should works.

**Comment by MohmadAyman** [comment]
Error sails-rest-api 

You don't seem to have a generator with the name sails-rest-api installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 0 registered generators run yo with the `--help` option.

**Comment by ghaiklor** [comment]
@MohmadAyman what happens if you install generator with yo tool in menu ?

**Comment by MohmadAyman** [comment]
i ran the yo and installed ```sails-angular``` just to verify that yo is alright, then i tried ```sails-rest-api``` and it just worked, thank!.

**Comment by ghaiklor** [comment]
@MohmadAyman seems you missed something. Glad it works :+1:
