### ISSUE TITLE
Client side call example desired

### ISSUE THREAD

**Issue by c835722** [ghaiklor/generator-sails-rest-api#25]
Can you provide an example client side call exhibiting general usage pattern?

**Comment by ghaiklor** [comment]
@c835722 I will add a little bit docs to wiki and readme soon, it's one of priorities to next minor version.

Answering to your question. The basic pattern begins from `/v1/` prefix, then controller's name and action. So, for example, `AuthController.js` -> `signin` will be `/v1/auth/signin`.

The same with `UserController.js` and REST routes. It have default actions in `UserController.js` named `create`, `find`, `findOne`, `update`, `destroy`. And client side calls to that will be `POST /v1/user`, `GET /v1/user`, `GET /v1/user/:id`, `PUT /v1/user/:id`, `DELETE /v1/user/:id`.

**Comment by c835722** [comment]
Yep, for background I am trying to test the assumed interaction and getting stuck on missing credentials out of a GET /v1/user/:id

**Comment by ghaiklor** [comment]
@c835722 I got you. If you look into `config/policies.js` you'll see 2 policies in use for `UserController`.

First one it's `isOurApp.js` which checks that your request contain `Application-Token` header with private token inside and second one checks if request has JWT token of authorized user.

So, right from the box you get private API and get all users you can only if you will be authorized. And, of course, you can modify it to fit your requirements. This is just most used behavior.

How get all users? Here the answer:

- Don't forgot to include `Application-Token` header with value from `api/policies/isOurApp.js` to all your requests;
- Make request to `/v1/auth/signin`, `/v1/auth/facebook` or `/v1/auth/twitter` and authorize yourself. You will get JWT token which you should use in all requests (except `AuthController`);
- And then you can make request to `/v1/user/:id` with `Application-Token: <isOurApp token>` and `Authorization: JWT <JWT token>` headers.

**Comment by c835722** [comment]
@ghaiklor I succeeded in calling a /v1/user/:id
The key consideration was calling the /v1/auth/signup route with credentials of username and password.
Further to this I can call the /v1/auth/signin when these are supplied as form-data along with the JWT token.

**Comment by ghaiklor** [comment]
@c835722 I have wrote a little bit documentation in wiki - https://github.com/ghaiklor/generator-sails-rest-api/wiki.
