### ISSUE TITLE
Wanna be part of Your Team

### ISSUE THREAD

**Issue by adrianeguez** [ghaiklor/generator-sails-rest-api#260]
Hello Guys,
I want to improve my skills on Continues, Delivery, Testing, Documentation and the other tools you are using, Also I have experience with sails, node, angular, yeoman, angular 1.x .
I am a backend and frontend developer with javascript.
I hope I can help you within this proyect.
Greetings

**Comment by ghaiklor** [comment]
@adrianeguez you are the part of open-source community, so you are already a part of our team 😺 You can check issues, take some and make PR. I'll review and help you with merging and releasing them. Check contributing guide first and you are ready to go.
