### ISSUE TITLE
Social Auth

### ISSUE THREAD

**Issue by tommymolto** [ghaiklor/generator-sails-rest-api#262]
Man, i'm striggling with the code here. In my debugs, /auth/social reaches till passport.authenticate , but is never calling the _onSocialStrategyAuth method. The token is right, appid, and strategyName as facebook-token.

What could be wrong?  My social.js is in this format:

```javascript
"use strict";

module.exports = {
  services: {
    social: {
      facebook: {
        clientID: "xxx",
        clientSecret: "xxx",
      },
      google: {
        clientId: 'xxx-xxx.apps.googleusercontent.com',
        clientSecret: 'xxx'
      }
    }
  }
};
```

**Comment by ghaiklor** [comment]
@tommymolto could you provide more information about this? What version are you using? I can't help with tracing the issue 'cause I'm not working with Sails anymore. 'll be glad if you fix the issue and send PR.

**Comment by ghaiklor** [comment]
Closing, reopen if you came back with an information.
