### ISSUE TITLE
Implement pluralized form only for REST models

### ISSUE THREAD

**Issue by ghaiklor** [ghaiklor/generator-sails-rest-api#27]
Right now when you enable `pluralize` in `config/blueprints.js` it will assign pluralized form to controllers like `AuthController`. That's no good, so need to fix it, maybe with overriding config in controller.

**Comment by ghaiklor** [comment]
https://github.com/balderdashy/sails/blob/master/lib/hooks/blueprints/index.js#L244

**Comment by IncoCode** [comment]
It can be done using following hook:
```js
var _ = require('lodash');

module.exports = function (sails) {
  return {
    initialize: function (cb) {
      sails.on('router:before', function () {
        if (!_.get(sails.config, 'blueprints.pluralize')) {
          return;
        }
        _.forEach(sails.middleware.controllers, function (controller, name) {
          if (!_.get(sails.models, name, false) && !_.get(controller, '_config.pluralize', false))
            _.set(controller, '_config.pluralize', false);
        });
      });

      cb();
    }
  }
};
```

**Comment by ghaiklor** [comment]
@IncoCode You can make simple hook in `api/hooks` for try out. And if everything works great then I can merge PR with this hook.
