### ISSUE TITLE
Application-Token ?

### ISSUE THREAD

**Issue by PiXeL16** [ghaiklor/generator-sails-rest-api#286]
Hi, 
Looking at old issues it looks like there was a policy `isOurApp.js` that handle the `Application-Token` private API authorization. Is that still present in another way?

**Comment by ghaiklor** [comment]
@PiXeL16 it had been removed.

**Comment by PiXeL16** [comment]
@ghaiklor Thanks for the response. Any way of doing it out of the box? Or does people normally roll their own solution?

**Comment by ghaiklor** [comment]
@PiXeL16 we heavy used it in our real projects and becomes that `ApplicationToken` is not really a necessary part of the projects. You can easily add it by yourself ;)

**Comment by PiXeL16** [comment]
Yes sure, I was just wondering if it was still supported.
Thanks!
