### ISSUE TITLE
npm test times out on windows

### ISSUE THREAD

**Issue by mikedevita** [ghaiklor/generator-sails-rest-api#291]
using the latest build of the generator, even setting the timeout to 60s on windows sails takes a really long time to lift, it'd be nice to know how to increase the timeout in istanbul, i added `--timeout 120s` to the mocha.opts but that doesn't always wor.

**Comment by ghaiklor** [comment]
@mikedevita check `yeoman-generator` version. I bumped it to v0.22.4, I guess, and got working test cases on Mac OS.

**Comment by mikedevita** [comment]
looks like that update breaks bash on windows 👎 

![image](https://cloud.githubusercontent.com/assets/2991640/19600355/7dc115e6-9759-11e6-98b1-b2520db45a08.png)

**Comment by ghaiklor** [comment]
@mikedevita seems like it relates to yo package itself.

**Comment by mikedevita** [comment]
yeah i think this is resolved now, it works fine for me now.
