### ISSUE TITLE
Document how to use the test/fixtures

### ISSUE THREAD

**Issue by mikedevita** [ghaiklor/generator-sails-rest-api#292]
i was using barrels to auto seed the db with test data, but i noticed theres a fixtures now included.. but its a different syntax and im not sure how to use this?

**Comment by ghaiklor** [comment]
@mikedevita these fixtures is just plain JS object which requires manually. Feel free to make a PR with updates 👍

**Comment by mikedevita** [comment]
ahh ok, well would you be open to using barrels?, i've never built a yeoman generator so im not sure how to get it to integrate, i'd need to do some research.

**Comment by ghaiklor** [comment]
@mikedevita you can read more about it here - http://yeoman.io/authoring/
