### ISSUE TITLE
JWT decoding error should return unauthorized

### ISSUE THREAD

**Issue by sercanov** [ghaiklor/generator-sails-rest-api#303]
In isAuthenticated.js when jwt authenticating fails, sends it to res.negotiate and return 500, i think it should be return unauthorized no matter what the cause is for decoding token. Don't you think so ? ^^

**Comment by ghaiklor** [comment]
@sercanov feel free to create a PR for it 👍 
We already added 401 error - https://github.com/ghaiklor/generator-sails-rest-api/blob/dev/generators/authentication/templates/api/policies/isAuthenticated.js#L12

**Comment by sercanov** [comment]
sure I will !
