### ISSUE TITLE
application not start.

### ISSUE THREAD

**Issue by satishverma143** [ghaiklor/generator-sails-rest-api#311]
i have used npm start to start application but not working.
also used node app.js but this is not working.
the error comes 
27 error 404 Registry returned 404 for GET on https://registry.npmjs.org/myrestapi
28 error 404
29 error 404 'myrestapi' is not in the npm registry.
30 error 404 You should bug the author to publish it (or use the name yourself!)
31 error 404 Note that you can also install from a
32 error 404 tarball, folder, http url, or git url.
33 verbose exit [ 1, true ]

**Comment by ghaiklor** [comment]
@satishverma143 it's not related to this package, read the logs carefully.

> 'myrestapi' is not in the npm registry.

We are not using this package at all, check your configurations on your side.

**Comment by satishverma143** [comment]
@ghaiklor this is my application name "myrestapi"

**Comment by ghaiklor** [comment]
@satishverma143 IDK, you need to check errors on your side. I've never seen this before.
