### ISSUE TITLE
does the generator support sails@beta 1.0.0 yet?

### ISSUE THREAD

**Issue by mikedevita** [ghaiklor/generator-sails-rest-api#312]
does the generator support sails@beta 1.0.0 yet?

**Comment by ghaiklor** [comment]
@mikedevita we need to do a lot of work to migrate from 0.11. For now, I don't have a much time for this. Feel free to create a PR with this functionality :)

**Comment by mikedevita** [comment]
thanks @ghaiklor its still in beta so i don't think its a huge rush yet, just curious if it was on the eventual roadmap.
