### ISSUE TITLE
how can i add autopopulate back in to the find and findOne blueprints?

### ISSUE THREAD

**Issue by mikedevita** [ghaiklor/generator-sails-rest-api#314]
and keep the pagination? I enabled `populate: true` in my `config/blueprints.js` and remove the `api/blueprints/(find|findOne).js` files but which allows me to auto populate records but i lose the the pagination stuff in the returned object.

**Comment by ghaiklor** [comment]
@mikedevita I believe, that's your custom logic and you should figure out in this howto on your own.
