### ISSUE TITLE
self.defaults is not a function

### ISSUE THREAD

**Issue by tomanagle** [ghaiklor/generator-sails-rest-api#325]
I get the following error when running npm start on a fresh install. 

```
node_modules\sails\lib\app\configuration\load.js:136
            var implicitDefaults = self.defaults(overrides.appPath || process.cwd());
                                        ^
TypeError: self.defaults is not a function
```

**Comment by ghaiklor** [comment]
@tomanagle seems like the issue with Sails itself. Error thrown from Sails internals.

**Comment by tomanagle** [comment]
Hi @ghaiklor, you're right that the problem is in sails.js

I was using Node v8.1.4 and downloaded to v6.11.1 LTS and it is now working.

Thank you
