### ISSUE TITLE
Move error codes from hardcoded values to config

### ISSUE THREAD

**Issue by ghaiklor** [ghaiklor/generator-sails-rest-api#34]
I think that the best practice will be move error codes like `E_BAD_REQUEST` or `E_USER_EXISTS` to some config file or any global object.

**Comment by IncoCode** [comment]
https://github.com/IncoCode/sails-service-error-codes/blob/dev/README.md#usage

**Comment by ghaiklor** [comment]
@IncoCode Still keep it in open, because we don't have strict structure for it. We need a board and free time :)
