### ISSUE TITLE
User signup

### ISSUE THREAD

**Issue by c835722** [ghaiklor/generator-sails-rest-api#35]
Hi,
I had a test that ran "Ok" against 0.4.0 tag to /signup a user.
In this it passed a username and password in the body.
Post the 0.5.1 code drop this test is fails.
When I check the user DB after the signup "Created" the username and password are not present as fields so when I try to later /signin this fails with "Missing credentials".
Is this a feature (and if so how to I now signin) or perhaps a bug?
Cheers.

**Comment by ghaiklor** [comment]
@c835722 can you provide your test case? I'll replicate it on my side.

**Comment by ghaiklor** [comment]
@c835722 I've checked history of `AuthController.js` from 0.4.0 and see that changed only response. Now I'm return not `200 OK` but `201 CREATED`. So you should expect for 201 HTTP code.

**Comment by c835722** [comment]
This was the [test] (https://gist.github.com/c835722/91e9dcf438b36f38ecc1) I was running against a service built using default yo parameters. Apologies up front if the error is on my side.

**Comment by ghaiklor** [comment]
@c835722 And on what line it breaks up? You can post here more additional info when you are running tests. Will better if you just copy\paste the whole testing process.

**Comment by c835722** [comment]
/usr/local/bin/node /Users/c835722/.usr/local/projects/quokka/quokka-api-probe-client/node_modules/mocha/bin/_mocha --reporter spec --ui bdd --reporter "/Users/c835722/Library/Application Support/IntelliJIdea14/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js" /Users/c835722/.usr/local/projects/quokka/quokka-api-probe-client/test
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjU0ZTZmYzc1ZGI2MmY2MTEwYWNhYzIwYyIsImlhdCI6MTQyNDQyNDA1MywiZXhwIjoxNDI0NTEwNDUzfQ.fWpj8X7TF76aZc2FKjXgmlCe_iWh1O1fwbvV6FH6Ct4
Error: done() invoked with non-Error: {"code":"E_UNAUTHORIZED","message":"Missing credentials","response":{}}
    at /Users/c835722/.usr/local/projects/quokka/quokka-api-probe-client/node_modules/mocha/lib/runnable.js:222:25
    at /Users/c835722/.usr/local/projects/quokka/quokka-api-probe-client/test/quokka-api-probe-service-unirest.js:86:58
    at Request.handleRequestResponse [as _callback] (/Users/c835722/.usr/local/projects/quokka/quokka-api-probe-client/node_modules/unirest/index.js:459:25)
    at Request.self.callback (/Users/c835722/.usr/local/projects/quokka/quokka-api-probe-client/node_modules/unirest/node_modules/request/request.js:373:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/c835722/.usr/local/projects/quokka/quokka-api-probe-client/node_modules/unirest/node_modules/request/request.js:1318:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/c835722/.usr/local/projects/quokka/quokka-api-probe-client/node_modules/unirest/node_modules/request/request.js:1266:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Process finished with exit code 1

**Comment by c835722** [comment]
Under 0.4.0 the signup was producing a valid username in the db.
After 0.4.0 the signup process is no longer inserting valid username so the subsequent signin fails.

**Comment by ghaiklor** [comment]
@c835722 This error appears only when you really forgot to send `username` and `password` fields in request:

> Error: done() invoked with non-Error: {"code":"E_UNAUTHORIZED","message":"Missing credentials","response":{}}

If user not found in database then you'll get this error

```javascript
            if (!user) {
                return next(null, false, {
                    code: "E_USER_NOT_FOUND",
                    message: username + " is not found"
                });
            }
```

So, I thinking that problem in request. Can you reproduce this bug manually with some REST client? Suppose that problem in `unirest` which can't send fields in request.

**Comment by c835722** [comment]
I can reproduce this via Postman.
Here is a Postman that follows the [wiki](https://github.com/ghaiklor/generator-sails-rest-api/wiki/How-to-use) convention but does not return the username and password in v0.5.1
```
POST /v1/auth/signup HTTP/1.1
Host: localhost:1337
application-token: 3c940cf3be9cda55e2ccaf4d1fdb1899
Cache-Control: no-cache
Postman-Token: b7935118-9ad1-c21d-810d-36fdf2372cc2
{
    "username": "c8357223",
    "password": "pass1word"
}
```
When I checkout the v0.4.0 tag && npm install && npm link && re-generate the above command succeeds so the test case is repeatable for me.

**Comment by ghaiklor** [comment]
@c835722 ok, I see. I'll take a look on this bug tomorrow.

**Comment by ghaiklor** [comment]
@c835722 I have researched on this and here the results.

Request:
```
POST /v1/auth/signup HTTP/1.1
Host: localhost:1337
Connection: close
User-Agent: Paw/2.1.1 (Macintosh; OS X/10.10.2) GCDHTTPRequest
Content-Length: 0
```

Response:
```
HTTP/1.1 201 Created
X-Powered-By: Express
Vary: X-HTTP-Method-Override
Content-Type: application/json; charset=utf-8
Content-Length: 566
Date: Sat, 21 Feb 2015 10:34:34 GMT
Connection: close

{
  "code": "CREATED",
  "message": "The request has been fulfilled and resulted in a new resource being created",
  "response": {
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjU0ZTg1ZjNhOThhNzZjOTdiOGIwNjYzMiIsImlhdCI6MTQyNDUxNDg3NCwiZXhwIjoxNDI0NjAxMjc0fQ.IpFALD7w3pK2nHQrZTK9AJvjVTQ-2KlqjfvXpqeevRY",
    "user": {
      "id": "54e85f3a98a76c97b8b06632",
      "firstName": "",
      "lastName": "",
      "photo": "",
      "phoneNumber": "",
      "createdAt": "2015-02-21T10:34:34.207Z",
      "updatedAt": "2015-02-21T10:34:34.207Z"
    }
  }
}
```

I can't replicate this bug. You must waiting for the response with 201 code.
