### ISSUE TITLE
Improve responses with underscore attributes

### ISSUE THREAD

**Issue by ghaiklor** [ghaiklor/generator-sails-rest-api#38]
When we are working with models declarations, we must follow JavaScript style guides. So any attribute will be named in camelCase. But when we send response, we must send in under_score style.

So my proposal it's replace camelCase attributes with under_score in responses.

**Comment by ghaiklor** [comment]
Question for discussion here - #31

**Comment by IncoCode** [comment]
Temporary solution:
```javascript
function strFromCamelCaseToUnderScore(str) {
  return str.replace(/([A-Z])/g, function (c) {
    return "_" + c.toLowerCase();
  });
}
 
function objToUnderscore(obj) {
  return _.transform(obj, function (result, value, key, arr) {
    var newKey = strFromCamelCaseToUnderScore(key);
    if (_.isObject(arr[key])) {
      result[newKey] = objToUnderscore(arr[key]);
    } else {
      result[newKey] = value;
    }
  });
}
```

**Comment by ghaiklor** [comment]
@IncoCode I'm starting to think about custom hook for Sails, as you proposed before. Because, I think, it shouldn't be hardcoded in responses and if someone want to install this one to own project without our generator - custom hook will do this.
