### ISSUE TITLE
Do you need to add views?

### ISSUE THREAD

**Issue by savager** [ghaiklor/generator-sails-rest-api#39]
Could benefit to see an example of adding a single view.

**Comment by ghaiklor** [comment]
@savager This generator useful for scaffolding backend part and only backend (REST API). Views are disabled by default. If you need generate project with views then better to use sails generator:

```shell
npm install -g sails
sails new myApp
```

But, if you need add view here, then you should clean `hooks` object in `.sailsrc` file. So your file will be with next content:

```
{
  "generators": {
      "modules": {}
  },
  "hooks": {}
}
```

Add configuration file `views.js` with next content:

```javascript
module.exports.views = {
    engine: 'ejs',
    layout: 'layout'
}
```

For more information you can go to Sails Anatomy - http://sailsjs.org/#!/documentation/anatomy/myApp

**Comment by ghaiklor** [comment]
So now I see, that I MUST add feature which allows generate not only backend by answering on question. So, my proposal is add question "Do you need only backend?" or kinda. If not, then I'll generate all other stuff. I'll add this to my roadmap.

**Comment by ghaiklor** [comment]
After some thoughts I decide to close this issue. Our generator's task - it's generate clean REST API. Without views, localization, etc... So this feature will not be implemented.
