### ISSUE TITLE
Running node app.js fails with error: missing sails-disk adaptor

### ISSUE THREAD

**Issue by orthodoc** [ghaiklor/generator-sails-rest-api#40]
Unable to run the server. Installing the sails-disk package with npm still leads to the following error stack
```
error: Trying to use unknown adapter, "sails-disk", in model `user`.
error: Are you sure that adapter is installed in this Sails app?
error: If you wrote a custom adapter with identity="sails-disk", it should be in this app's adapters directory.
error: Otherwise, if you're trying to use an adapter named `sails-disk`, please run `npm install sails-disk@0.11.x`
```
node 0.12.1

**Comment by orthodoc** [comment]
My mistake. Running the following command took care of the error:

```
npm install sails-disk --save
```
Running the same with the -g flag didn't help in the first place!!

**Comment by ghaiklor** [comment]
@orthodoc yeah, know issue. The problem, that when I'm parsing AST from generated sources, I can't parse list of adapters which you choose. So, for now, you should install needed sails adapter manually. Will be fixes in future releases :smiley:
