### ISSUE TITLE
No route to match the PATCH action verb

### ISSUE THREAD

**Issue by orthodoc** [ghaiklor/generator-sails-rest-api#41]
PUT /model/:id results in 

```js
{
  "code": "OK",
  "message": "Operation is successfully executed",
  "data": {
    ...
  }
}
```
PATCH /model/:id results in

```js
{
  "code": "E_NOT_FOUND",
  "message": "The requested resource could not be found but may be available again in the future",
  "data": {}
}
```

**Comment by ghaiklor** [comment]
@orthodoc this issue is specific for Sails framework and already done PR for that feature - https://github.com/balderdashy/sails/pull/2006

**Comment by orthodoc** [comment]
:+1: Absence of tests and merge conflicts are preventing the PR, and this was filed ages ago. Wow!
