### ISSUE TITLE
Creating a user via signup throws a not null constraint error with postgresql

### ISSUE THREAD

**Issue by orthodoc** [ghaiklor/generator-sails-rest-api#42]
The `signup` method defined in the AuthController creates the user with this function:  `User.create(req.allParams())`. 

`console.log(req.allParams())` reveals that the id is undefined.

Postgresql throws up the following error as a result:
`Error (E_UNKNOWN) :: Encountered an unexpected error`
`error: null value in column "id" violates not-null constraint`

**Comment by orthodoc** [comment]
Removing the id parameter by passing `delete req.allParams().id` leads to successful creation of the user. Adding `autoPK: true` to the config/model.js is not necessary.

Thanks to [RWOverdijk](https://github.com/RWOverdijk) for pointing this out.

**Comment by ghaiklor** [comment]
@orthodoc so seems that fix for that will be change `signup` action to this:

```javascript
var body = req.allParams();
delete body.id;

User.create(body).then(...)
```

**Comment by ghaiklor** [comment]
Done in this way:

```javascript
signup: function (req, res) {
    User
      .create(_.omit(req.allParams(), 'id'))
      .then(function (user) {
        return {
          // TODO: replace with new type of cipher service
          token: CipherService.create('jwt', {id: user.id}).hashSync(),
          user: user
        };
      })
      .then(res.created)
      .catch(res.serverError);
  }
```

**Comment by orthodoc** [comment]
:+1:
