### ISSUE TITLE
Failure after initial install of npm packages

### ISSUE THREAD

**Issue by eswann** [ghaiklor/generator-sails-rest-api#43]
When I attempt to generate a new project...I'm taken through the steps to create the project/DB etc...  All of the files get created, some packages get installed...then error is thrown.  Any ideas?

I tried with both Postgres and Mongo.  I'm using 0.9

```shell
C:\Users\eric_swann\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\index.js:101
      Object.keys(deps).forEach(function (dep) {
             ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at C:\Users\eric_swann\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\index.js:101:14
    at Array.forEach (native)
    at C:\Users\eric_swann\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\index.js:100:13
    at C:\Users\eric_swann\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\node_modules\async\lib\async.js:254:17
    at done (C:\Users\eric_swann\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\node_modules\async\lib\async.js:135:19)
    at C:\Users\eric_swann\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\node_modules\async\lib\async.js:32:16
    at C:\Users\eric_swann\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\node_modules\async\lib\async.js:251:21
    at getDeps (C:\Users\eric_swann\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\index.js:110:14)
    at C:\Users\eric_swann\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\index.js:95:5
```

**Comment by ghaiklor** [comment]
@eswann seems that this issue Windows specific. The problem can be in relative path and how Windows handle it in difference from Unix\Linux.

Can you reproduce it on other platform ?

**Comment by ghaiklor** [comment]
Or you can try fix that issue in` dependency-check` module for you specific case. Then you can create PR to https://github.com/maxogden/dependency-check
But I'm going to create own parsing AST with detective, so it can be fixed soon.

**Comment by eswann** [comment]
Yeah I assumed it was a windows FS issue, perhaps a path depth situation.  Unfortunately I'm constrained to a win machine for this project.... :(

**Comment by ghaiklor** [comment]
@eswann great. I leave this issue opened and in future releases try to fix that (if I found somewhere notebook with Windows)

**Comment by ghaiklor** [comment]
This issue is forwards to dependency-check module and need to fix that there.

**Comment by ghaiklor** [comment]
@eswann can you check the latest version of generator (from dev branch) ? I suppose that issue with Windows machines is fixed.

**Comment by eswann** [comment]
Nice, will do!

**Comment by ghaiklor** [comment]
@eswann I was hoping that you try it out 4 days ago :) Right now I'm fully re-writing generator with ES6 support and re-composability. So you will be able to generate project structure from different generators. For instance, `yo sails-rest-api:services` will generate only services part of the project.

**Comment by eric-swann-q2** [comment]
Sweet!  Sounds awesome.

**Comment by ghaiklor** [comment]
@eric-swann-q2 @eswann you can check the alpha version of generator-sails-rest-api. All issues is fixed with Windows.

**Comment by ghaiklor** [comment]
Fixed in the latest version. I've just removed this module and dependencies is installing in other way now.
