### ISSUE TITLE
Posting to auth/facebook returns E_NOT_FOUND error (404)

### ISSUE THREAD

**Issue by orthodoc** [ghaiklor/generator-sails-rest-api#44]
I am making a $http request to v1/auth/facebook route
Have defined the baseUrl, appToken as variables in the same file (not in the code over here). Successfully implemented signup and signin using similiar methods. My understanding from reading the wiki is that I need to pass the access_token obtained from facebook as params, and so the code below.
```
 var fbReq = function(aToken) {                                                                                                                         
           return {                                                                                                                                         
             url: baseUrl + '/facebook',                                                                                                                    
             headers: {                                                                                                                                     
               'application-token': appToken                                                     
             },                                                                                                                                             
             method: 'POST',                                                                                                                                
             params: {'access_token': aToken},                                                                                                              
           };                                                                                                                                               
         },      
```
Then calling the req through a service method

```
service.authFb = function(bToken) {                                                                                                                    
      console.log(fbReq(bToken));                                                                                                                          
       $http(fbReq(bToken))                                                                                                                                 
         .then(function(response) {                                                                                                                         
           q.resolve(response);                                                                                                                             
         }, function(error){                                                                                                                                
           console.log(error);                                                                                                                              
           q.reject("There was a problem logging into api server");                                                                                     
         });                                                                                                                                                
         return q.promise;                                                                                                                                  
     };
return service; 
```

Or do I need to pass in the auth_token as a header??

**Comment by orthodoc** [comment]
Passing it as a plain header:

```
{
'access_token': <token>,
}
```
doesn't work as well. Do I need to to encode the acess_token? The docs at the wiki are not clear on this step for the facebook strategy.

**Comment by ghaiklor** [comment]
@orthodoc you should read changelog :smiley: 
When I face the problem with social profiles, I understand, that declaring separate route for each social - it's bad move, because all the logic is the same for each social.
So I create route `/v1/auth/social` which accepts `type` parameter where you say which social you want to use for authorization. Take a look at `AuthController.social`.
This move allow to me adding new social services just providing new passport strategy without modifying existing routes and logic.
And don't forgot, that all the structure is in settling process :smiley:

**Comment by orthodoc** [comment]
Ok.
Changed the url to `auth/social`
Added the following to params: `{ "access_token": <token>, 'type': 'facebook' }`
And I got the error: `error: column user.socialProfiles.facebook.id does not exist`

Looking at the User.js model file, the socialProfiles attribute is described as:
`socialProfiles: { type: 'object', defaults: {} }`

 I couldn't find 'object' type in the list of attributes currently available in [waterline](https://github.com/balderdashy/waterline#attributes). Is the socialProfiles supposed to be a json  or array attribute type?

**Comment by ghaiklor** [comment]
@orthodoc hm... very strange. You can try set to `json`. This logic is going in `config/passport.js` at `_onSocialStrategyAuth`. You can take a look here and try to fix that.

**Comment by orthodoc** [comment]
Possibly related to balderdashy/sails-postgresql#36

However, changing the type to `json` returns the same error as above. I am looking at `_onSocialStrategyAuth`.

**Comment by ghaiklor** [comment]
@orthodoc you can try switch to another adapter. If with another adapter it works, then this bug really specific for adapter.

**Comment by orthodoc** [comment]
If I switch the connection to `memory` it works but not with `postgresql`. Filed an issue balderdashy/sails-postgresql#155

**Comment by ghaiklor** [comment]
@orthodoc thinking about this issue. Also can be, that postgresql adapter doesn't support dot.notations. If so, then we need to make it ourself :smile:

**Comment by orthodoc** [comment]
@ghaiklor, how do I do that? Any guidance on that...

**Comment by ghaiklor** [comment]
@orthodoc if to be honest, I don't know for sure how to implement this in adapter-level. But again, returning to your error snippet. Seems that adapter can't find facebook id and failing. In normal adapters, `findOrCreate` creating record if not founded. Maybe issue with `find` action in adapter. Can you try replace `findOrCreate` with `find` and see what happens?

**Comment by orthodoc** [comment]
When I replace the `findOrCreate` method with `find` I get exactly the same error: 
`error: column user.socialProfiles.facebook.id does not exist`

If I use the method `create` instead, then I get the following error: 
```
Error (E_VALIDATION) :: 1 attribute is invalid
...
Invalid attributes sent to User:
    • email
      • `undefined` should be a string (instead of "null", which is a object)
      • "email" validation rule failed for input: null
      • "required" validation rule failed for input: null
```
I am really stumped on this one.

**Comment by orthodoc** [comment]
@ghaiklor any comments on [this comment](https://github.com/balderdashy/sails-postgresql/issues/155#issuecomment-96780011). [@dmarcelino](https://github.com/dmarcelino) seems to concur with you.

> As I suspected, your issue is the find because waterline does not support the dot . notation nor it  supports querying inside a json. The way to go about querying nested associations would be to use associations (docs).
> The way to go about querying nested associations would be to use associations (docs).


Does using associations mean that I should create another model socialProfiles and use a one-to-many association between user and socialProfile?

**Comment by ghaiklor** [comment]
@orthodoc it's better. If you can call `create` and it works (never mind to email validation rule) - it's better.
And no, `socialProfiles` it's just storage for you social profiles, so I can find you if you try to signin again. You don't need set association with this field.

**Comment by orthodoc** [comment]
@ghaiklor, I can confirm that I am able to use the `create` method to create the user record but then I guess I have to write out a query to check if the record exists when the user returns. Maybe I need to change the variable `criteria` to be email instead of the social id.

**Comment by orthodoc** [comment]
Bt the way, I just checked that with `jsonb` type which is available with postgresql-9.4, I can do a deep nested query in this way:
```javascript
User.query("select * from "user" where "socialProfiles" #> '{"facebook", "id"}' = '"10xxxxxxxxxxxx415"'");
```
It does return a unique record, and also a null record when there's no match.

**Comment by ghaiklor** [comment]
@orthodoc so seems that @sails-postgresql can implement this ?

**Comment by ghaiklor** [comment]
This issue is forwards to sails-postgresql adapter.

**Comment by orthodoc** [comment]
`jsonb` does allow deep nested query but `sails-postgresql` doesn't. Which means that the following code:
```
User.query("select * from "user" where "socialProfiles" #> '{"facebook", "id"}' = '"10xxxxxxxxxxxx415"'", function(err, result) {...});
``` 
will return errors. :disappointed:

**Comment by ghaiklor** [comment]
@orthodoc you can send this information to sails-postgresql repo. I believe, that it can be done, if you did this using native queries. Also, I thinking about another structure for saving because of issues like this. But I'll return to this when I done with services modules.
