### ISSUE TITLE
Make sails-hook-responses-underscore

### ISSUE THREAD

**Issue by ghaiklor** [ghaiklor/generator-sails-rest-api#55]
Discussion here - #38 
My proposal it's make another npm module kinda *sails-hook-response-underscore* and just include it in our generator as dependency.

@IncoCode need to discuss about it.

**Comment by IncoCode** [comment]
How about to override ```jsonx``` function which in ```response``` object?
```javascript
module.exports = function (sails) {
  return {
    initialize: function (cb) {
      sails.on('router:route', function (opt) {
        if (opt.req.myHookDone || !_.isFunction(opt.res.jsonx))
          return;
        opt.req.myHookDone = true;
        var jsonx = opt.res.jsonx;
        opt.res.jsonx = function (obj) {
          var res = objToUnderscore(obj);
          jsonx(res);
        };
      });
      cb();
    }
  }
};
```
Maybe there's a better way to override it.

**Comment by ghaiklor** [comment]
@IncoCode hm... it's better than before. If `jsonx` is really function that calls everytime on response, that we can do that way.

**Comment by IncoCode** [comment]
> All of the built-in response handlers use ```res.jsonx``` when JSON is requested by the client.
https://github.com/balderdashy/sails/issues/1918#issuecomment-61551367

https://github.com/balderdashy/sails/blob/master/lib/hooks/responses/index.js#L204
@ghaiklor and you call it in every response.

**Comment by IncoCode** [comment]
Yeah, we can override it in another way:
```javascript
module.exports = function (sails) {
  return {
    routes:{
      after:{
        'all /*': function overrideJsonx(req, res, next) {
          var jsonx = res.jsonx;
          res.jsonx = function (obj) {
            var res = objToUnderscore(obj);
            jsonx(res);
          };
          next();
        }
      }
    }
  }
};
```

**Comment by ghaiklor** [comment]
@IncoCode I see, ok. You can try and will look into this. If solution is so simple, then we even don't need hook for that. Just place it somewhere in middlewares at all.

**Comment by ghaiklor** [comment]
Closed due compatibility issues with request in snake_case too.
