### ISSUE TITLE
Blueprint find() does not return X-Total-Count

### ISSUE THREAD

**Issue by willjleong** [ghaiklor/generator-sails-rest-api#59]
Proposed Fix: add line res.set('X-Total-Count', count) inside the .spead() in api/blueprints/find.js

**Comment by ghaiklor** [comment]
@willjleong I'd thinking about this, but `X-Total-Count` is deprecated header. That's why we move it to root response object. Anyway, I'll mark this for discussion, maybe as a legacy code it will be added.

**Comment by willjleong** [comment]
Agreed, is a less popular header now, but there are plenty of front-end libraries that expect the header for pagination. This was the solution I used when integration sails with ng-admin.  It could be potentially added as an config option, but by no means necessary.

**Comment by ghaiklor** [comment]
2a85e0a8c38cb1712a3a9fc2133bd86388491146
