### ISSUE TITLE
Add new controller

### ISSUE THREAD

**Issue by mhipo1364** [ghaiklor/generator-sails-rest-api#62]
Thanks for this useful repo, but I don't know how add a new controller to system which this module can handle it as other controllers which is called by /v1/CONTROLLER_NAME/... ?

**Comment by IncoCode** [comment]
```sails generate controller <controller name>```
http://sailsjs.org/documentation/concepts/controllers/generating-controllers
If you want to create model with controller use the following command:
```sails generate api <name>```

**Comment by mhipo1364** [comment]
thanks, I'm familiar with these commands, but after creating controller, I have to add controller route and put `/v1` at the begin of route

**Comment by IncoCode** [comment]
Works fine for me :confused:
@ghaiklor

**Comment by ghaiklor** [comment]
@mhipo1364 Sails is automatically bind controller's actions to appropriate routes. See `config/blueprints.js` file for customizing this. If you want to add controller, you can just create new file in `api/controllers` and it's automatically bind all actions to `/v1/<CONTROLLER_NAME>/<ACTION_NAME>` route.

So, anyway, if you have strict steps for reproduce this bug, please share.

**Comment by mhipo1364** [comment]
I have VoucherController with this content:
```javascript
module.exports = {
	index: function(req, res) {
        var user = User.findOneByUsername('moefar').exec(function(error, users){
            res.json(users);
        });
        //console.log(user);
        //res.json({'user': user});
        },
    };
```

and this is my blueprint:
```javascript
module.exports.blueprints = {
  /**
   * When enabled, GET, POST, PUT and DELETE routes will be generated for everyone of a controller's actions
   * @type {Boolean}
   */
  actions: true,

  /**
   * When enabled, `index` action will be default action
   * @type {Boolean}
   */
  index: true,

  /**
   * REST blueprints are the automatically generated routes Sails uses to expose a conventional REST API
   * on top of a controller's `find`, `findOne`, `create`, `update`, and `destroy` actions
   * @type {Boolean}
   */
  rest: true,

  /**
   * Shortcut routes are simple helpers to provide access to a controller's CRUD methods from your browser's URL bar
   * @type {Boolean}
   */
  shortcuts: false,

  /**
   * An optional mount path for all blueprint routes on a controller, including `rest`, `actions`, and `shortcuts`
   * @type {String}
   */
  prefix: '/api',

  /**
   * An optional mount path for all blueprint routes on a controller, including only `rest`
   * @type {String}
   */
  restPrefix: '',

  /**
   * Whether to pluralize controller names in blueprint routes
   * @type {Boolean}
   */
  pluralize: true,

  /**
   * Whether the blueprint controllers should populate model fetches with data
   * from other models which are linked by associations
   * @type {Boolean}
   */
  populate: true,

  /**
   * Whether to run Model.watch() in the find and findOne blueprint actions
   * @type {Boolean}
   */
  autoWatch: false,

  /**
   * The default number of records to show in the response from a "find" action
   * @type {Number}
   */
  defaultLimit: 5
};
```

**Comment by aars** [comment]
One obvious issue is your prefix is `/api`, not `/v1`

**Comment by mhipo1364** [comment]
@aars : yeah I know that, I write my problem with default config to not confusing. :smiley: 

But, my problem is not this

**Comment by ghaiklor** [comment]
@mhipo1364 still don't get it. You have `VoucherController` and action `index`. Your route to this - `api/voucher` (in your case)

**Comment by ghaiklor** [comment]
@mhipo1364 I'm using `v1` prefix, because in future you can change API to your application, but you must left old API also.

So you just create\update Sails app, set in `config/blueprints` prefix to `v2` and you got 2 apps that handles old API and new one.

You have created controller, that works fine by `/api/voucher`. Everything is works.
