### ISSUE TITLE
actions in controller http verbs

### ISSUE THREAD

**Issue by mhipo1364** [ghaiklor/generator-sails-rest-api#63]
I need to fix my actions on one particular http verbs, for example, when user wants to create new content, just POST verb can do it and when he use another verb, application respond with `405 - Method Not Allowed` exception. How can I do this?

**Comment by ghaiklor** [comment]
@mhipo1364 it's your custom behavior then. You can override actions `create`, `find`, `findOne`, `update` or `destroy` in your controller and set all the checks here.

Or using policies and apply them to controllers that you want to cover with that.

**Comment by mhipo1364** [comment]
Dear @ghaiklor really thanks for quick response, would kindly help me to handle this issue?

I really need this but I do't have any idea to implement it

**Comment by ghaiklor** [comment]
@mhipo1364 each controller has pre-defined `create` (POST), `find` and `findOne` (GET), `update` (PUT) and `destroy` (DELETE) actions. When you don't have those actions in your controller and make request `POST /v1/model`, for instance, then executes pre-defined action called `create` in your controller.

You can override this behavior just define your own action like

```javascript
// api/controllers/foo.js
module.exports = {
  create: function(req, res) {
    // your logic here
  }
};
```

In this case route will be the same `POST /v1/model` but executes your overried `create` action, not pre-defined.

So in places, where you want to make this feature you can just override actions -> make some your logic -> and if this is the case for `405`, then just `res.send` with 405 code.

**Comment by mhipo1364** [comment]
@ghaiklor : really thanks :+1:

**Comment by ghaiklor** [comment]
@mhipo1364 if this helps, I can close this issue. Re-open it if you need it :+1:
