### ISSUE TITLE
Read some useful data from cache

### ISSUE THREAD

**Issue by mhipo1364** [ghaiklor/generator-sails-rest-api#64]
Hi

I have some data which are very common and I need to fetch them so many times, how can I read them from redis?

**Comment by ghaiklor** [comment]
@mhipo1364 Just use sails-redis adapter for working with Redis database. You can specify as many connections in `config/connection.js` file as you want. And then just use this connections to describe models and which storage\adapter this model should use.

**Comment by mhipo1364** [comment]
@ghaiklor : Thanks

Could I use both adapters for model, then sails handle to add data to these adapters or I need to create 2 models for supporting this feature?

**Comment by ghaiklor** [comment]
@mhipo1364 as I know model can manage only one connection. If you need to manage one model with many different connections, then maybe you're looking for wrong solution :smiley:

**Comment by mhipo1364** [comment]
@ghaiklor : Yes I know, I'm `Django` developer, in `Django` we have a `cacheops` which manages all models caches and work with signals, that means when a record creates or updates, `cacheops` automatically updates cached data on redis. I'm searching something like this in `sails.js`

**Comment by ghaiklor** [comment]
@mhipo1364 in this case you don't need be tight to SailsJS. You can look any solutions for NodeJS.
