### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by mhipo1364** [ghaiklor/generator-sails-rest-api#65]
Hi

How can I send email using MailerService? Is there any boilerplate for calling and its options?

**Comment by ghaiklor** [comment]
@mhipo1364 did you install last stable version from npm or dev version from GitHub ?

I'm asking because last version from dev has separated services and you can find docs here - https://github.com/ghaiklor/sails-service-mailer

**Comment by mhipo1364** [comment]
@ghaiklor  I get it from here:
https://www.npmjs.com/package/generator-sails-rest-api

but I don't have sails-service-mailer in my node-modules directory

**Comment by ghaiklor** [comment]
@mhipo1364 so you are using last stable version where our new changes don't applied. You can install `sails-service-mailer` from repository above and just follow the README. You can replace your existing service with new one.

New version of generator-sails-rest-api will be in few weeks where all this will be by default.

**Comment by mhipo1364** [comment]
:+1:
