### ISSUE TITLE
M2M relationship in get model

### ISSUE THREAD

**Issue by mhipo1364** [ghaiklor/generator-sails-rest-api#66]
Hi

I need an advice, I have a M2M relationship, then I want to get data from one of entities which has relation to specific record on other entity. How can I use find blueprint to get it by default ?

**Comment by willjleong** [comment]
Check this out http://stackoverflow.com/questions/23446484/sails-js-populate-nested-associations
You will have to apply this idea to your find() with a forEach() probably.  You can override the blueprint find() if you put it in the controller
``` 
    module.export = {
      find: function(req, res) {/** custom code goes here**/}
    }
```

**Comment by mhipo1364** [comment]
Thanks @willjleong , but I thought this package has this option, because it checks if we want to see which associates.

**Comment by willjleong** [comment]
Currently, Sails.js/Waterline only supports 1 level deep populations. Deeper populations need to be implemented in a way similar to the link I posted.  It's true this package does have custom blueprints that support auto-populations, but they still only go one level deep.  You need to override each blueprint action in the controller if you want a certain action like findOne() or find() to return populated data with a depth greater than 1 level deep.

**Comment by ghaiklor** [comment]
@willjleong @mhipo1364 Some guy from Waterline implement deep cursor, so I think in future Sails adapters can handle deep populations.
