### ISSUE TITLE
socket.io error 400 

### ISSUE THREAD

**Issue by mhipo1364** [ghaiklor/generator-sails-rest-api#80]
Hi guys

I have a situation, when I ran my project with pm2 (with single cpu core) , everything was fine, but when I ran it again with -i 2 switch, I got error 400 in /socket.io !!

What is the problem ? How can I fix it? 

**I notified via newrelic**

**Comment by ghaiklor** [comment]
@mhipo1364 We don't support sockets here. Basically, I've disabled them because REST API doesn't need it.

**Comment by mhipo1364** [comment]
@ghaiklor I don't use it in entire of project, but when I deploy project using pm2 and cluster mode( -i 2 ), I think it use socket.io for some reason, isn't it?

**Comment by ghaiklor** [comment]
@mhipo1364 strange. I've never saw this issue before.
@IncoCode some ideas ?

**Comment by mhipo1364** [comment]
@ghaiklor: error happens on /socket.io : 

![Image of Yaktocat](http://oi62.tinypic.com/wr1655.jpg)

It happens 30 times in average every single seconds!!

**Comment by IncoCode** [comment]
Maybe, sockets are not disabled? [`.sailsrc`](https://github.com/ghaiklor/generator-sails-rest-api/blob/dev/generators/app/templates/.sailsrc#L7-L12) file has no `sockets: false`.

**Comment by ghaiklor** [comment]
@IncoCode @mhipo1364 they are moved to separate npm module. I suppose it should be disabled.
@mhipo1364 try to add `"sockets": false` into your `.sailsrc` file.

**Comment by mhipo1364** [comment]
Sure, thanks guys. :+1: 

I will put my result here after testing

**Comment by mhipo1364** [comment]
Yeah, exactly, we should add `"sockets": false` in `.sailsrc` file.

@ghaiklor @IncoCode Thanks

**Comment by ghaiklor** [comment]
@IncoCode we need to make hot-fix for it :+1:

**Comment by ghaiklor** [comment]
Fixed and released under patch version

**Comment by mhipo1364** [comment]
@ghaiklor :+1:
