### ISSUE TITLE
JWT is pinging the database?

### ISSUE THREAD

**Issue by komocode** [ghaiklor/generator-sails-rest-api#82]
Using JWT seems to be hitting the database to verify the user. Isn't the whole point of JWT is to avoid pinging the database in the first place? Otherwise we may as well use sessions and store the sessions in the DB

**Comment by komocode** [comment]
Nevermind, I was confused.

**Comment by ghaiklor** [comment]
@komocode Why are you confused ? We need to make query to database because we don't have sessions.

**Comment by komocode** [comment]
I misunderstood JWT. I thought JWT as long as you can decode the payload successfully, that would be the verification point.

**Comment by ghaiklor** [comment]
@komocode you're right, we can store all the model in the payload. But don't forgot that JWT is just base64, so you can decode base64 and get payload from JWT. That's why we store only user's id and other information get from database.

**Comment by komocode** [comment]
Right, that would be too costly to transmit/decode, and would need to refresh every time user data changes. I got it now, thanks!
