### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by mhipo1364** [ghaiklor/generator-sails-rest-api#87]
I'm wondering how can I update this package to latest version ?

Because I've changed `User`, ... models, also `UserController`.

**Comment by ghaiklor** [comment]
@mhipo1364 you can just call `npm -g update` if you had installed `generator-sails-rest-api` in global scope and call the generator again. But don't forgot that it can rewrite your current project.

**Comment by mhipo1364** [comment]
@ghaiklor: yeah, I'm worry about overriding, thanks man :+1:
