### ISSUE TITLE
populate data from relation in blueprints

### ISSUE THREAD

**Issue by mhipo1364** [ghaiklor/generator-sails-rest-api#90]
Hi

I need to populate data in blueprints `GET` , for example I want to get `contents` which have some particular `tags`, How can I do this?

I'm so confuse about node.js ORM capabilities

**Comment by ghaiklor** [comment]
@mhipo1364 You can use default `populate` blueprint for this purpose. Here is the routes `GET /:model/:parentId/:relation` and `GET /:model/:parentId/:relation/:id`. So, you can make `GET /v1/users/<USER_ID>/contents`.

But, if you want to lookup for specific records based on your criteria we have a problem here. You can try make smth like `GET /v1/contents?where={tags: [1,2,3]}`

**Comment by mhipo1364** [comment]
Wow, so painful :|

Thanks dear @ghaiklor

**Comment by mhipo1364** [comment]
How can I get populated relations via `GET  /:model/:parentId/:relation` ?

**Comment by ghaiklor** [comment]
@mhipo1364 you just make `GET /users/<USER_ID>/assoc` request and that's it. For instance.

```javascript
// api/models/User.js
module.exports = {
  attributes: {
    comments: {
      collection: 'Comment',
      via: 'user'
    }
  }
};

// api/models/Comment.js
module.exports = {
  attributes: {
    user: {
      model: 'User',
      via: 'comments'
    }
  }
};
```

In this case you make `GET /v1/users/<USER_ID/comments` and get all comments of specified user.

**Comment by mhipo1364** [comment]
yes I know, I want to populate other relations, for example comments has some relations with other entities, I want to get them also

**Comment by ghaiklor** [comment]
@mhipo1364 this one is called deep populate and can't be achieved via blueprints, yet... I hope.

**Comment by ghaiklor** [comment]
Waiting for Waterline 0.11 with deep cursor and maybe then we can do this.
