### ISSUE TITLE
Error on creating a new project

### ISSUE THREAD

**Issue by gadonski** [ghaiklor/generator-sails-rest-api#91]
i am trying to create a new project, but occurs these errors:

$> yo sails-rest-api
Checking for updates...
OK... You are using the latest version 0.10.4

Database questions:
? Choose database adapter: MySQL
? Type your database host: localhost
? Type your database name: sails-rest-api
? Type your database username: root
? Type your database password:

Application questions:
? Type your application name: one
? Type your secret for this application: (daded7dee4b16e54b45f0a5f8b614debd1da434483ab9281
? Type your secret for this application: 1a1a1a

Service questions:
? Select which services you want to use: CipherService, HashService, StorageService
? Which type of storage providers you want to use: Amazon
   create package.json
   create .jshintrc
   create .sailsrc
   create api\adapters\.gitkeep
 
    ........

   create test\unit\responses\unauthorized.test.js
```javascript
C:\Users\andre.gadonski\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\index.js:102
      Object.keys(deps).forEach(function (dep) {
             ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at C:\Users\andre.gadonski\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\index.js:102:14
    at Array.forEach (native)
    at C:\Users\andre.gadonski\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\index.js:101:13
    at C:\Users\andre.gadonski\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\node_modules\async\lib\async.js:251:17
    at done (C:\Users\andre.gadonski\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\node_modules\async\lib\async.js:132:19)
    at C:\Users\andre.gadonski\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\node_modules\async\lib\async.js:32:16
    at C:\Users\andre.gadonski\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\node_modules\async\lib\async.js:248:21
    at getDeps (C:\Users\andre.gadonski\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\index.js:113:14)
    at C:\Users\andre.gadonski\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\index.js:96:5

```

Node version: v0.12.4
Npm version:

**Comment by ghaiklor** [comment]
@gadonski I've seen this issue before on Windows machines. I can't reproduce this, 'cause I'm running this on OSX and Linux. If you find the solutions, you can make PR that fix that.

**Comment by IncoCode** [comment]
https://github.com/maxogden/dependency-check/issues/30

**Comment by ghaiklor** [comment]
@gadonski can you check the latest version of generator from dev branch ? I've updated patched dependency-check for Windows.

**Comment by gadonski** [comment]
I will try on Sunday. Today i am on a Mac.
Em 12/09/2015 18:22, "Eugene Obrezkov" <notifications@github.com> escreveu:

**Comment by ghaiklor** [comment]
Fixed
