### ISSUE TITLE
Sails port

### ISSUE THREAD

**Issue by Clan-Utility** [ghaiklor/generator-sails-rest-api#96]
I put ```port:1337``` in both config/local.js and config/http.js. But when sails lift, it still uses port 3000. Where should I change the port?
Btw, where is sails.log disabled? I mean, sails.log.error, sails.log.info ... is OK, but sails.log(.....) logs nothing. I set level: 'info' in config/log.js

**Comment by ghaiklor** [comment]
@Clan-Utility check `config/env` folder. There is specific configuration for environment.

**Comment by Clan-Utility** [comment]
Does this mean port in config/local.js & config/http/js will always be overridden by config/env?

**Comment by ghaiklor** [comment]
@Clan-Utility yes. Environment-specific configuration has priority.

**Comment by Clan-Utility** [comment]
Sorry that I have further question.
Regarding sails.log, I know you have set in config/log.js 

    module.exports.log.custom = new winston.Logger({

to change the behavior of the default sails.log() function.

But the problem is that, even if I set ```log: { level: 'silly' }``` in config/env/development.js, all the errors generated by sails or throw new Error are suppressed (not shown in console & log file), unless I catch the error and call sails.log(error) manually.

**Comment by ghaiklor** [comment]
@Clan-Utility it looks like a real bug. I'll take a look closer.

**Comment by Clan-Utility** [comment]
Alright, figured out why the original sails.js logs errors by default.
Put in api/responses/serverError.js

    // Log error to console
    if (data !== undefined) {
        sails.log.error('Sending 500 ("Server Error") response: \n',data);
    }
    else sails.log.error('Sending empty 500 ("Server Error") response');

**Comment by Clan-Utility** [comment]
Plus, it may be a good idea to put this in serverError.js as well

    if (sails.config.environment === 'production') {
        delete response.error;
    }
