### ISSUE TITLE
config/models.js

### ISSUE THREAD

**Issue by Clan-Utility** [ghaiklor/generator-sails-rest-api#97]
Even if I set connection: 'mongo' in config/models.js, sails still uses disk.db. Why is that?

**Comment by ghaiklor** [comment]
@Clan-Utility the same. Check `config/env` folder.

**Comment by Clan-Utility** [comment]
Yes, that's it!  When open the project folder in Sublime Text 3 (build 3083), config/env folder is not shown!

**Comment by ghaiklor** [comment]
@IncoCode can you check this issue ? I'm wondering why @Clan-Utility doesn't get `env` folder.

@Clan-Utility what version are you using ?

**Comment by Clan-Utility** [comment]
v0.10.4, for Sublime Text 3 (build 3083). 

It is a problem of ST, which does not list folder named 'env' in its side bar, even for other path.

**Comment by ghaiklor** [comment]
@Clan-Utility so there is no problems then ?
Strange that Sublime is not showing `env` folder.
